"""create delivery notes and delivery note lines

Revision ID: 0137b663b529
Revises: 6a6fffec7d19
Create Date: 2026-09-29 19:34:52.526299

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0137b663b529'
down_revision: str | Sequence[str] | None = '6a6fffec7d19'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='DRAFT', nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_notes_business_id'), 'delivery_notes', ['business_id'], unique=False)
    op.create_index(op.f('ix_delivery_notes_order_id'), 'delivery_notes', ['order_id'], unique=False)
    op.create_table('delivery_note_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_note_id', sa.Integer(), nullable=False),
    sa.Column('order_line_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['delivery_note_id'], ['delivery_notes.id'], ),
    sa.ForeignKeyConstraint(['order_line_id'], ['order_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_note_lines_delivery_note_id'), 'delivery_note_lines', ['delivery_note_id'], unique=False)
    op.create_index(op.f('ix_delivery_note_lines_order_line_id'), 'delivery_note_lines', ['order_line_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_delivery_note_lines_order_line_id'), table_name='delivery_note_lines')
    op.drop_index(op.f('ix_delivery_note_lines_delivery_note_id'), table_name='delivery_note_lines')
    op.drop_table('delivery_note_lines')
    op.drop_index(op.f('ix_delivery_notes_order_id'), table_name='delivery_notes')
    op.drop_index(op.f('ix_delivery_notes_business_id'), table_name='delivery_notes')
    op.drop_table('delivery_notes')
    # ### end Alembic commands ###
