"""create invoice tables

Revision ID: 36344f288a54
Revises: 0137b663b529
Create Date: 2026-10-01 19:09:23.880842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36344f288a54'
down_revision: Union[str, Sequence[str], None] = '0137b663b529'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('next_number', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'code', name='uq_invoice_series_business_code')
    )
    op.create_index(op.f('ix_invoice_series_business_id'), 'invoice_series', ['business_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('invoice_series_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='DRAFT', nullable=False),
    sa.Column('invoice_type', sa.String(length=20), server_default='STANDARD', nullable=False),
    sa.Column('series', sa.String(length=20), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('full_number', sa.String(length=50), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('operation_date', sa.Date(), nullable=True),
    sa.Column('issuer_legal_name', sa.String(length=150), nullable=False),
    sa.Column('issuer_tax_id', sa.String(length=20), nullable=False),
    sa.Column('issuer_address', sa.String(length=255), nullable=False),
    sa.Column('issuer_postal_code', sa.String(length=10), nullable=False),
    sa.Column('issuer_city', sa.String(length=100), nullable=False),
    sa.Column('issuer_province', sa.String(length=100), nullable=False),
    sa.Column('issuer_country_code', sa.String(length=2), nullable=False),
    sa.Column('customer_legal_name', sa.String(length=150), nullable=False),
    sa.Column('customer_tax_id', sa.String(length=20), nullable=True),
    sa.Column('customer_address', sa.String(length=250), nullable=True),
    sa.Column('customer_postal_code', sa.String(length=10), nullable=True),
    sa.Column('customer_city', sa.String(length=100), nullable=True),
    sa.Column('customer_province', sa.String(length=100), nullable=True),
    sa.Column('customer_country_code', sa.String(length=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['invoice_series_id'], ['invoice_series.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'full_number', name='uq_invoices_business_full_number'),
    sa.UniqueConstraint('business_id', 'series', 'number', name='uq_invoices_business_series_number')
    )
    op.create_index(op.f('ix_invoices_business_id'), 'invoices', ['business_id'], unique=False)
    op.create_index('ix_invoices_business_status', 'invoices', ['business_id', 'status'], unique=False)
    op.create_index(op.f('ix_invoices_customer_id'), 'invoices', ['customer_id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_series_id'), 'invoices', ['invoice_series_id'], unique=False)
    op.create_table('invoice_delivery_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('delivery_note_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['delivery_note_id'], ['delivery_notes.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delivery_note_id', name='uq_invoice_delivery_notes_delivery_note_id'),
    sa.UniqueConstraint('invoice_id', 'delivery_note_id', name='uq_invoice_delivery_notes_invoice_delivery_note')
    )
    op.create_index(op.f('ix_invoice_delivery_notes_delivery_note_id'), 'invoice_delivery_notes', ['delivery_note_id'], unique=False)
    op.create_index(op.f('ix_invoice_delivery_notes_invoice_id'), 'invoice_delivery_notes', ['invoice_id'], unique=False)
    op.create_table('invoice_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('delivery_note_line_id', sa.Integer(), nullable=False),
    sa.Column('order_line_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['delivery_note_line_id'], ['delivery_note_lines.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['order_line_id'], ['order_lines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delivery_note_line_id', name='uq_invoice_lines_delivery_note_line_id')
    )
    op.create_index(op.f('ix_invoice_lines_delivery_note_line_id'), 'invoice_lines', ['delivery_note_line_id'], unique=False)
    op.create_index(op.f('ix_invoice_lines_invoice_id'), 'invoice_lines', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoice_lines_order_line_id'), 'invoice_lines', ['order_line_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_lines_order_line_id'), table_name='invoice_lines')
    op.drop_index(op.f('ix_invoice_lines_invoice_id'), table_name='invoice_lines')
    op.drop_index(op.f('ix_invoice_lines_delivery_note_line_id'), table_name='invoice_lines')
    op.drop_table('invoice_lines')
    op.drop_index(op.f('ix_invoice_delivery_notes_invoice_id'), table_name='invoice_delivery_notes')
    op.drop_index(op.f('ix_invoice_delivery_notes_delivery_note_id'), table_name='invoice_delivery_notes')
    op.drop_table('invoice_delivery_notes')
    op.drop_index(op.f('ix_invoices_invoice_series_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_customer_id'), table_name='invoices')
    op.drop_index('ix_invoices_business_status', table_name='invoices')
    op.drop_index(op.f('ix_invoices_business_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_invoice_series_business_id'), table_name='invoice_series')
    op.drop_table('invoice_series')
    # ### end Alembic commands ###
